import Head from "next/head";
import Header from "../components/Header";
import { useUser } from "@auth0/nextjs-auth0";

export default function Home() {
  const { user, error, isLoading } = useUser();

  // you can use the error and loading state to show an error message or a loading spinner while loading.
  if (isLoading) {
    return (
      <div className="text-5xl font-semibold text-center text-indigo-600">
        ...loading{" "}
      </div>
    );
  }

  if(error){
    return (
      <div className="text-5xl font-semibold text-center text-indigo-600">
        {error.message}
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userLoggedIn={user} />
      <h1 className="text-4xl mt-6 font-bold text-indigo-500 text-center">
        Welcome to the Nextjs-Auth0 Demo Application.
      </h1>
      <div className="max-w-[500px] border-4 border-indigo-400 rounded-lg p-6 mx-auto text-3xl mt-16 font-bold text-indigo-700 text-center">
        {user && (
          <p className="mb-6">
            Welcome <span className="text-amber-600">{user.name}</span>
          </p>
        )}
        {!user && (
          <p>You are Not signed In, Please Sign In to view the Secret Pages.</p>
        )}
      </div>
    </div>
  );
}
